---
title: "Untitled"
output: html_document
date: "2023-11-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load("tidyverse", "lme4", "png", "grid")
```


```{r}
# Set the seed for reproducibility
set.seed(52)

# Number of participants
n_participants <- 50

# Create a data frame with participant information
participants <- data.frame(
  participant_id = 1:n_participants,
  group = sample(c(0, 1), n_participants, replace = TRUE)
)

# Number of trials per condition
n_trials <- 100

# Initialize data frame to store simulated data
sim_data <- data.frame(
  participant_id = rep(participants$participant_id, each = n_trials),
  group = rep(participants$group, each = n_trials),
  condition = rep(rep(c("DoubleCongruence", "MusicViolation", "LanguageViolation", "DoubleViolation"), each = 5), times = n_participants),
  music_violation = rep(c(0, 1, 0, 1), each = 5),
  language_violation = rep(c(0, 0, 1, 1), each = 5),
  stimuli = rep(c("Joint", "Separate"), each = n_trials/2),
  elan = 0,
  eran = 0
)

# Simulate data for ELAN and ERAN
sim_data$eran[sim_data$condition != "DoubleCongruence" & sim_data$condition != "LanguageViolation"] <- rnorm(sum(sim_data$condition != "DoubleCongruence" & sim_data$condition != "LanguageViolation"), mean = 0, sd = 0.5)
sim_data$elan[sim_data$condition != "DoubleCongruence" & sim_data$condition != "MusicViolation"] <- rnorm(sum(sim_data$condition != "DoubleCongruence" & sim_data$condition != "MusicViolation"), mean = 0, sd = 0.5)

# Set ERAN values based on specified means
sim_data$eran[sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Joint" & sim_data$group == 0] <- rnorm(sum(sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Joint" & sim_data$group == 0), mean = -0.7, sd = 0.5)
sim_data$eran[sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Joint" & sim_data$group == 1] <- rnorm(sum(sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Joint" & sim_data$group == 1), mean = -2, sd = 0.5)
sim_data$eran[sim_data$condition == "MusicViolation" & sim_data$stimuli == "Joint" & sim_data$group == 0] <- rnorm(sum(sim_data$condition == "MusicViolation" & sim_data$stimuli == "Joint" & sim_data$group == 0), mean = -1, sd = 0.5)
sim_data$eran[sim_data$condition == "MusicViolation" & sim_data$stimuli == "Joint" & sim_data$group == 1] <- rnorm(sum(sim_data$condition == "MusicViolation" & sim_data$stimuli == "Joint" & sim_data$group == 1), mean = -2.4, sd = 0.5)

sim_data$eran[sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Separate" & sim_data$group == 0] <- rnorm(sum(sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Separate" & sim_data$group == 0), mean = -1.3, sd = 0.5)
sim_data$eran[sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Separate" & sim_data$group == 1] <- rnorm(sum(sim_data$condition == "DoubleViolation" & sim_data$stimuli == "Separate" & sim_data$group == 1), mean = -2.3, sd = 0.5)
sim_data$eran[sim_data$condition == "MusicViolation" & sim_data$stimuli == "Separate" & sim_data$group == 0] <- rnorm(sum(sim_data$condition == "MusicViolation" & sim_data$stimuli == "Separate" & sim_data$group == 0), mean = -1.7, sd = 0.5)
sim_data$eran[sim_data$condition == "MusicViolation" & sim_data$stimuli == "Separate" & sim_data$group == 1] <- rnorm(sum(sim_data$condition == "MusicViolation" & sim_data$stimuli == "Separate" & sim_data$group == 1), mean = -2.7, sd = 0.5)

# Set ERAN values to NA for Language Violation
sim_data$eran[sim_data$condition == "LanguageViolation"] <- NA

# Set ELAN values to NA for Music Violation
sim_data$elan[sim_data$condition == "MusicViolation"] <- NA

# Print the first few rows of the simulated data
head(sim_data)

```


```{r}
sim_data$group <- as.factor(sim_data$group)
```

```{r}
img <- readPNG("/Users/villiamjensen/Documents/nisse.png")

img <- img[, , c(1, 2, 3, 4 * 0.4)]

g <- rasterGrob(img, interpolate=TRUE, height = 0.5, width = 0.65, vjust = 0.05)
```


```{r}
sim_data %>% filter(condition == "DoubleViolation" | condition == "MusicViolation") %>% 
  ggplot(aes(x = condition, y = eran, fill = group)) +
   annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_boxplot() + 
  facet_wrap(~stimuli) + 
  scale_y_reverse() +
  theme_bw() + 
  labs(x = "Condition", y = "ERAN", fill = "Group") +
  scale_fill_manual(values = c("firebrick", "olivedrab"), labels = c("Non-Musician", "Musician"))

```


```{r}
sim_data %>% 
  ggplot(x = condition, )
```



```{r}
bayes_m1 <- brms::brm(eran ~ condition,
                         data = sim_data, chains = 3,
                         iter = 3000, warmup = 1000)

bayes_m2 <- brms::brm(eran ~ condition * group + (1 | participant_id), 
                      data = sim_data, chains = 3,
                         iter = 3000, warmup = 1000)

#model1 <- glmer(data = sim_data, eran ~ music_violation + (1|participant_id))

#summary(model1)
```

```{r}
summary(bayes_m)

summary(bayes_m2)
```

